#-- E_CARD_ACTION --

E_CARD_ACTION = {                                
    0x00:'ACTION_CARD_FOREIGN',
    0x20:'ACTION_CARD_DISCARDED',
    0x40:'ACTION_CARD_HACKED',
    0x50:'ACTION_CARD_BAD_DATA',
    0x60:'ACTION_CARD_NO_DATA',
    0x80:'ACTION_CARD_UNLOCKED',
    0x81:'ACTION_CARD_UNLOCKED_1',
    0x82:'ACTION_CARD_UNLOCKED_2',
    0x83:'ACTION_CARD_UNLOCKED_3',
    0x84:'ACTION_CARD_UNLOCKED_4',
    0x85:'ACTION_CARD_UNLOCKED_5',
    0x86:'ACTION_CARD_UNLOCKED_6',
    0x87:'ACTION_CARD_UNLOCKED_7',
    0x70:'ACTION_QR_UNLOCKED',
    0x71:'ACTION_QR_BLOCKED',
    0x72:'ACTION_QR_UNKNOWN',       

    0x85:'CARD_OK',
    0xFF:'ACTION_CARD_UNKNOWN'

}

#-- E_KNOWN_DEVICE_TYPES ----

DL_AIS_100 = 0
DL_AIS_20  = 1
DL_AIS_30  = 2
DL_AIS_35  = 3
DL_AIS_50  = 4
DL_AIS_110 = 5
DL_AIS_LOYALITY = 6

#AIS START == BASE BAT USB
DL_AIS_37 = 7

#Half-Duplex // Barcode NFC Reader
DL_AIS_BMR = 11

#Half-Duplex // new base half duplex
DL_AIS_BASE_HD = 12

#Half-Duplex > DL_BASEHD_CONTROL_SDK
DL_XRCA = 20  
DL_AIS_SYSTEM_TYPES_COUNT = DL_UNKNOWN_DEVICE = 0xFF
